fastlane_require 'dotenv'
default_platform(:ios)

platform :ios do

  desc 'Clean any generated Xcode project and pods'
  lane :clean do
    Dir.chdir('../') do
      sh('rm -rf *.xcodeproj')
      sh('rm -rf *.xcworkspace')
      sh('rm -rf *.ipa')
      sh('rm -rf Pods')
    end
  end

  desc 'Generate Xcode project and install dependencies'
  lane :generate do
    generate()
  end  

  def generate
    clean
    Dotenv.overload '../.env'
    update_info_plist

    Dir.chdir('../') do
      xcodegen_config = ENV['XCODEGEN_CONFIG_FILE']
      if xcodegen_config.nil?
        sh('xcodegen -q')
      else
        sh("xcodegen -q -s #{xcodegen_config}")
      end
    end

    cocoapods(
      try_repo_update_on_error: true
    )
  end

  def update_info_plist
    app_path = ENV['APP_INFO_PLIST']
    widget_path = ENV['WIDGET_INFO_PLIST']

    set_info_plist_value(path: app_path, key: 'CFBundleName', value: ENV['APP_NAME'])
    set_info_plist_value(path: app_path, key: "CFBundleShortVersionString", value: ENV['BUNDLE_VERSION_STRING'])
    set_info_plist_value(path: app_path, key: "CFBundleVersion", value: ENV['BUNDLE_VERSION'])
    set_info_plist_value(path: app_path, key: "CFBundleIdentifier", value: ENV['APP_BUNDLE_IDENTIFIER'])
    set_info_plist_value(path: app_path, key: "CFBundleExecutable", value: '${EXECUTABLE_NAME}')
    set_info_plist_value(path: app_path, key: "NSSupportsLiveActivities", value: ENV['SUPPORTS_LIVE_ACTIVITIES'])
    set_info_plist_value(path: app_path, key: "UIUserInterfaceStyle", value: ENV['UI_USER_INTERFACE_STYLE'])
    set_info_plist_value(path: app_path, key: "UISupportedInterfaceOrientations", value: [ENV['INTERFACE_ORIENTATIONS_PORTRAIT'], ENV['INTERFACE_ORIENTATIONS_UPSIDE_DOWN']])

    set_info_plist_value(path: widget_path, key: "CFBundleIdentifier", value: ENV['WIDGET_BUNDLE_IDENTIFIER'])
    set_info_plist_value(path: widget_path, key: "NSExtension", subkey: "NSExtensionPointIdentifier", value: 'com.apple.widgetkit-extension')
  end

end